apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claims-api-secret
  namespace: claims-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: claims-api-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: enterprise-eks-gitops/dev/claims-api
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: enterprise-eks-gitops/dev/claims-api
        property: DB_PASSWORD