apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-api
  namespace: claims-dev
  labels:
    app: claims-api
    environment: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: claims-api
  template:
    metadata:
      labels:
        app: claims-api
        environment: dev
    spec:
      containers:
        - name: claims-api
          image: 398370989042.dkr.ecr.us-east-1.amazonaws.com/enterprise-eks-gitops-dev-claims-api:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"