replicaCount: 2

image:
  repository: 398370989042.dkr.ecr.us-east-1.amazonaws.com/enterprise-eks-gitops-dev-claims-api
  pullPolicy: Always
  tag: "dev"

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    external-dns.alpha.kubernetes.io/hostname: claims-api.dev.yaya626.com
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:398370989042:certificate/203a5f1d-2897-49a3-86b3-de2d10f1c559
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 20
  periodSeconds: 20

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10