name: Security Scan

on:
  push:

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Scan
        run: |
          echo "Running security scan"